# Simple workflow for deploying static content to GitHub Pages
name: Build app

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
      
      - name: Build app
        run: msbuild hram.sln /p:configuration=Release /p:platform=x64

      - name: Create zip file
        run: Compress-Archive x64/Release/hram.exe hram.zip

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{github.event.release.tag_name}} hram.zip
          gh release upload ${{github.event.release.tag_name}} x64/Release/hram.exe
